import { en } from "zod/v4/locales";
import { env } from "./env";

export const config = {
  port: env.PORT,

  nodeEnv: env.NODE_ENV,

  mongoUri: env.MONGODB_URI,

  jwt: {
    secret: env.JWT_SECRET,
    expiresIn: env.JWT_EXPIRES_IN,
  },
  BCRYPT_SALT_ROUNDS: env.BCRYPT_SALT_ROUNDS,
  DATABASE_URL: env.DATABASE_URL,
  ACCOUNT_LOCK_DURATION_MINUTES: env.ACCOUNT_LOCK_DURATION_MINUTES,
  MAX_FAILED_LOGIN_ATTEMPTS: env.MAX_FAILED_LOGIN_ATTEMPTS,
  JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET!,
  JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET!,
  JWT_ACCESS_EXPIRES_IN: env.JWT_ACCESS_EXPIRES_IN!,
  JWT_REFRESH_EXPIRES_IN: env.JWT_REFRESH_EXPIRES_IN!,
};