import { env } from "./env";

export const config = {
  port: env.PORT,

  nodeEnv: env.NODE_ENV,

  mongoUri: env.MONGODB_URI,

  jwt: {
    secret: env.JWT_SECRET,
    expiresIn: env.JWT_EXPIRES_IN,
  },
  BCRYPT_SALT_ROUNDS: env.BCRYPT_SALT_ROUNDS,
  DATABASE_URL: env.DATABASE_URL,
  ACCOUNT_LOCK_DURATION_MINUTES: env.ACCOUNT_LOCK_DURATION_MINUTES,
  MAX_FAILED_LOGIN_ATTEMPTS: env.MAX_FAILED_LOGIN_ATTEMPTS,
  JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET!,
  JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET!,
  JWT_ACCESS_EXPIRES_IN: env.JWT_ACCESS_EXPIRES_IN!,
  JWT_REFRESH_EXPIRES_IN: env.JWT_REFRESH_EXPIRES_IN!,
  CLOUDINARY_CLOUD_NAME: env.CLOUDINARY_CLOUD_NAME!,
  CLOUDINARY_API_KEY: env.CLOUDINARY_API_KEY!,
  CLOUDINARY_API_SECRET: env.CLOUDINARY_API_SECRET!,
  REDIS_URL: env.REDIS_URL,
  RAZORPAY_KEY_ID: env.RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET: env.RAZORPAY_KEY_SECRET,
  RAZORPAY_WEBHOOK_SECRET: env.RAZORPAY_WEBHOOK_SECRET,
  EMAIL_PROVIDER: env.EMAIL_PROVIDER,
  RESEND_API_KEY: env.RESEND_API_KEY,
  EMAIL_FROM: env.EMAIL_FROM
};
